language: ruby
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode

gemfile:
  Gemfile
  .gemfiles/gemfile-rails-3.1.0
  .gemfiles/gemfile-rails-3.1.1
  .gemfiles/gemfile-rails-3.1.2
